export const STATIONS = {
  110: {"name": "À Punt", "type": "Tranvia"},
    182: {"name": "Aeroport", "type": "Metro"},
    190: {"name": "Alacant", "type": "Tranvia"},
    69: {"name": "Alameda", "type": "Metro"},
    60: {"name": "Albalat dels Sorells", "type": "Metro"},
    2: {"name": "Alberic", "type": "Metro"},
    79: {"name": "Alboraia Palmaret", "type": "Metro"},
    56: {"name": "Alboraia Peris Aragó", "type": "Metro"},
    128: {"name": "Alfauir", "type": "Metro"},
    9: {"name": "Alginet", "type": "Metro"},
    57: {"name": "Almàssera", "type": "Metro"},
    192: {"name": "Amado Granell - Montolivet", "type": "Tranvia"},
    121: {"name": "Amistat", "type": "Metro"},
    25: {"name": "Àngel Guimerà", "type": "Metro"},
    120: {"name": "Aragó", "type": "Metro"},
    8: {"name": "Ausiàs March", "type": "Metro"},
    73: {"name": "Av. del Cid", "type": "Metro"},
    122: {"name": "Ayora", "type": "Metro"},
    108: {"name": "Bailén", "type": "Metro"},
    53: {"name": "Benaguasil", "type": "Metro"},
    82: {"name": "Benicalap", "type": "Tranvia"},
    28: {"name": "Beniferri", "type": "Metro"},
    67: {"name": "Benimaclet", "type": "Metro/Tranvia"},
    41: {"name": "Benimàmet", "type": "Metro"},
    6: {"name": "Benimodo", "type": "Metro"},
    39: {"name": "Bétera", "type": "Metro"},
    94: {"name": "Beteró", "type": "Tranvia"},
    30: {"name": "Burjassot", "type": "Metro"},
    31: {"name": "Burjassot - Godella", "type": "Metro"},
    99: {"name": "Cabanyal", "type": "Tranvia"},
    43: {"name": "Campament", "type": "Metro"},
    27: {"name": "Campanar", "type": "Metro"},
    103: {"name": "Campus", "type": "Tranvia"},
    40: {"name": "Cantereria", "type": "Metro"},
    127: {"name": "Canyamelar", "type": "Metro"},
    7: {"name": "Carlet", "type": "Metro"},
    1: {"name": "Castelló", "type": "Metro"},
    194: {"name": "Ciutat Arts i Ciències - Justícia", "type": "Tranvia"},
    70: {"name": "Colón", "type": "Metro"},
    16: {"name": "Col·legi El Vedat", "type": "Metro"},
    98: {"name": "Dr. Lluch", "type": "Tranvia"},
    48: {"name": "El Clot", "type": "Metro"},
    29: {"name": "Empalme", "type": "Metro/Tranvia"},
    65: {"name": "Entrepins", "type": "Metro"},
    11: {"name": "Espioca", "type": "Metro"},
    130: {"name": "Estadi Ciutat de València", "type": "Metro"},
    68: {"name": "Facultats - Manuel Broseta", "type": "Metro"},
    177: {"name": "Faitanar", "type": "Metro"},
    100: {"name": "Fira València", "type": "Tranvia"},
    80: {"name": "Florista", "type": "Tranvia"},
    59: {"name": "Foios", "type": "Metro"},
    52: {"name": "Fondo de Benaguasil", "type": "Metro"},
    10: {"name": "Font Almaguer", "type": "Metro"},
    124: {"name": "Francesc Cubells", "type": "Metro/Tranvia"},
    45: {"name": "Fuente del Jarro", "type": "Metro"},
    119: {"name": "Gallipont - Torre del Virrei", "type": "Metro"},
    81: {"name": "Garbí", "type": "Tranvia"},
    32: {"name": "Godella", "type": "Metro"},
    125: {"name": "Grau - La Marina", "type": "Tranvia"},
    38: {"name": "Horta Vella", "type": "Metro"},
    23: {"name": "Jesús", "type": "Metro"},
    5: {"name": "L'Alcúdia", "type": "Metro"},
    50: {"name": "L'Eliana", "type": "Metro"},
    95: {"name": "La Cadena", "type": "Tranvia"},
    46: {"name": "La Canyada", "type": "Metro"},
    92: {"name": "La Carrasca", "type": "Tranvia"},
    113: {"name": "La Coma", "type": "Tranvia"},
    183: {"name": "La Cova", "type": "Metro"},
    105: {"name": "La Granja", "type": "Tranvia"},
    63: {"name": "La Pobla de Farnals", "type": "Metro"},
    51: {"name": "La Pobla de Vallbona", "type": "Metro"},
    184: {"name": "La Presa", "type": "Metro"},
    47: {"name": "La Vallesa", "type": "Metro"},
    42: {"name": "Les Carolines - Fira", "type": "Metro"},
    115: {"name": "Ll. Llarga - Terramelar", "type": "Tranvia"},
    54: {"name": "Llíria", "type": "Metro"},
    66: {"name": "Machado", "type": "Metro"},
    180: {"name": "Manises", "type": "Metro"},
    123: {"name": "Marítim", "type": "Metro/Tranvia"},
    84: {"name": "Marxalenes", "type": "Tranvia"},
    114: {"name": "Mas del Rosari", "type": "Tranvia"},
    185: {"name": "Masia de Traver", "type": "Metro"},
    37: {"name": "Masies", "type": "Metro"},
    3: {"name": "Massalavés", "type": "Metro"},
    62: {"name": "Massamagrell", "type": "Metro"},
    34: {"name": "Massarrojos", "type": "Metro"},
    58: {"name": "Meliana", "type": "Metro"},
    75: {"name": "Mislata", "type": "Metro"},
    76: {"name": "Mislata Almassil", "type": "Metro"},
    35: {"name": "Moncada - Alfara", "type": "Metro"},
    49: {"name": "Montesol", "type": "Metro"},
    4: {"name": "Montortal", "type": "Metro"},
    196: {"name": "Moreres", "type": "Tranvia"},
    61: {"name": "Museros", "type": "Metro"},
    197: {"name": "Natzaret", "type": "Tranvia"},
    126: {"name": "Neptú", "type": "Tranvia"},
    74: {"name": "Nou d'Octubre", "type": "Metro"},
    195: {"name": "Oceanogràfic", "type": "Tranvia"},
    12: {"name": "Omet", "type": "Metro"},
    129: {"name": "Orriols", "type": "Metro"},
    19: {"name": "Paiporta", "type": "Metro"},
    55: {"name": "Palau de Congressos", "type": "Tranvia"},
    111: {"name": "Parc Científic", "type": "Tranvia"},
    44: {"name": "Paterna", "type": "Metro"},
    22: {"name": "Patraix", "type": "Metro"},
    18: {"name": "Picanya", "type": "Metro"},
    13: {"name": "Picassent", "type": "Metro"},
    24: {"name": "Pl. Espanya", "type": "Metro"},
    96: {"name": "Platja Malva-rosa", "type": "Tranvia"},
    97: {"name": "Platja les Arenes", "type": "Tranvia"},
    87: {"name": "Pont de Fusta", "type": "Tranvia"},
    178: {"name": "Quart de Poblet", "type": "Metro"},
    193: {"name": "Quatre Carreres", "type": "Tranvia"},
    64: {"name": "Rafelbunyol", "type": "Metro"},
    15: {"name": "Realón", "type": "Metro"},
    85: {"name": "Reus", "type": "Tranvia"},
    186: {"name": "Riba-roja de Túria", "type": "Metro"},
    33: {"name": "Rocafort", "type": "Metro"},
    181: {"name": "Roses", "type": "Metro"},
    191: {"name": "Russafa", "type": "Tranvia"},
    21: {"name": "Safranar", "type": "Metro"},
    86: {"name": "Sagunt", "type": "Tranvia"},
    179: {"name": "Salt de l'Aigua", "type": "Metro"},
    78: {"name": "Sant Isidre", "type": "Metro"},
    104: {"name": "Sant Joan", "type": "Tranvia"},
    131: {"name": "Sant Miquel dels Reis", "type": "Metro"},
    14: {"name": "Sant Ramon", "type": "Metro"},
    77: {"name": "Santa Rita", "type": "Metro"},
    36: {"name": "Seminari - CEU", "type": "Metro"},
    93: {"name": "Tarongers - Ernest Lluch", "type": "Tranvia"},
    112: {"name": "Tomás y Valiente", "type": "Tranvia"},
    17: {"name": "Torrent", "type": "Metro"},
    107: {"name": "Torrent Avinguda", "type": "Metro"},
    132: {"name": "Tossal del Rei", "type": "Metro"},
    83: {"name": "Trànsits", "type": "Tranvia"},
    88: {"name": "Trinitat", "type": "Tranvia"},
    26: {"name": "Túria", "type": "Metro"},
    91: {"name": "Universitat Politècnica", "type": "Tranvia"},
    20: {"name": "València Sud", "type": "Metro"},
    188: {"name": "València la Vella", "type": "Metro"},
    102: {"name": "Vicent Andrés Estellés", "type": "Tranvia"},
    90: {"name": "Vicente Zaragozá", "type": "Tranvia"},
    71: {"name": "Xàtiva", "type": "Metro"}
  };

  